//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Pop.rc
//
#define IDC_MOVE                        3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_POPTYPE                     129
#define IDD_SPEED                       130
#define IDR_OLD_MAINFRAME               130
#define IDC_DRAGHAND                    144
#define IDC_PIN                         145
#define IDC_SPAWN                       147
#define IDC_ZAP                         148
#define IDC_REPLICATE                   149
#define IDB_BIGSKY                      165
#define IDB_BUM                         166
#define IDB_EARTH                       167
#define IDB_FACE                        168
#define IDB_GNARLY                      169
#define IDB_SPRING                      170
#define IDB_SUN                         171
#define IDB_UFO                         172
#define IDD_OPENGLINFO                  182
#define IDB_EXPLODE1                    183
#define IDB_EXPLODE2                    184
#define IDB_EXPLODE3                    185
#define IDB_STREET                      193
#define IDD_StereoDialog                196
#define IDD_ABOUTBOX1                   197
#define IDB_BIGWATER_1TO2               203
#define IDB_YELLOWBLACKMARBLE_2TO1      206
#define IDB_AQUATRAPEZOIDS              207
#define IDB_SMOOTHBRICK_2TO1            208
#define IDB_GREENMOLD_2TO1              209
#define IDB_BEIGEFOAM                   210
#define IDB_PALEBLUESCROLLS             211
#define IDB_PURPLEWIGGLES               213
#define IDD_DIALOG1                     216
#define IDB_SMOOTHBRICK                 218
#define IDB_ABOUT                       222
#define IDD_OPTIONS                     223
#define IDD_STATUS_BAR                  225
#define IDD_MAIN_STATE                  226
#define IDD_WEAPON_SELECTION            227
#define IDD_GAME_OVER                   228
#define IDC_SPEED                       1000
#define IDC_UPDATESPERSECOND            1002
#define IDC_STATICINFO                  1006
#define IDC_STATICCOMMENT               1007
#define IDC_Reset                       1008
#define IDC_FOCALLEN                    1009
#define IDC_SPINFOCAL                   1010
#define IDC_CAMOFFSET                   1011
#define IDC_SPINCAM                     1012
#define IDC_LINK                        1021
#define IDC_CR                          1022
#define IDC_INFO                        1023
#define IDC_SELECT_PLAYER               1024
#define IDC_PLANET                      1026
#define IDC_PLANET_IMG                  1027
#define IDC_PLAYER_COLOR                1028
#define IDC_PLAYER_NAME                 1029
#define IDC_AMMO_LIST                   1030
#define IDC_POWER_TEXT                  1030
#define IDC_BUY                         1031
#define IDC_SELL                        1032
#define IDC_CLEAR                       1033
#define IDC_MONEY                       1034
#define IDC_PLANET_DESC                 1035
#define IDC_SELECT_WEAPON               1036
#define IDC_PLANET_INFO                 1037
#define IDC_POWER                       1041
#define IDC_ANGLE                       1042
#define IDC_WEAPON_NAME                 1043
#define IDC_SPIN2                       1045
#define IDC_SPIN_ANGLE                  1045
#define IDC_PLAYER_HP                   1046
#define IDC_COLOR_BUTTON                1047
#define IDC_FIRE                        1048
#define IDC_PASS                        1049
#define IDC_TIME                        1056
#define IDC_NAME                        1057
#define IDC_SUR                         1059
#define IDC_OK                          1060
#define ID_VIEW_COLOREDBUBBLES          32771
#define ID_VIEW_POPSOUND                32772
#define ID_VIEW_BONKSOUND               32773
#define ID_GAME_3D                      32775
#define ID_GAME_HUGE                    32777
#define ID_GAME_JUMBLED                 32778
#define ID_GAME_SMALL                   32779
#define ID_GAME_MEDIUM                  32780
#define ID_GAME_LARGE                   32781
#define ID_VIEW_XRAYBUBBLES             32783
#define ID_GAME_PLAYSOUNDS              32784
#define ID_GAME_RESTART                 32785
#define ID_VIEW_PINCURSOR               32793
#define ID_VIEW_DRAGGERCURSOR           32794
#define ID_WINDOW_AUTOTILE              32798
#define ID_WINDOW_AUTOFOCUS             32799
#define ID_HELP_USERSGUIDE              32801
#define ID_GAME_SPEED                   32802
#define ID_GAME_ANIMATE                 32803
#define ID_VIEW_ARROWCURSOR             32808
#define ID_FILE_SEED_SIMPLEPOLYGONS     32809
#define ID_FILE_SEED_FANCYPOLYGONS      32810
#define ID_FILE_SEED_POLYPOLYGONS       32811
#define ID_VIEW_SPAWNCURSOR4            32812
#define ID_VIEW_SPAWNCURSOR             32813
#define ID_VIEW_ZAPCURSOR5              32819
#define ID_VIEW_ZAPCURSOR               32821
#define ID_GAME_TRIPLEPOLYPOLYGONS      32824
#define ID_GAME_ASTEROIDS               32825
#define ID_VIEW_REPLICATECURSOR6        32826
#define ID_VIEW_REPLICATECURSOR         32832
#define ID_GAME_BITMAPS                 32833
#define ID_GAME_ASSORTED                32834
#define ID_GAME_WRAP                    32836
#define ID_GAME_BACKGROUND              32837
#define ID_VIEW_PLAYCURSOR              32838
#define ID_VIEW_PLAYGAME                32839
#define ID_PLAYER_EASYKEYS              32841
#define ID_PLAYER_CARKEYS               32842
#define ID_PLAYER_SPACESHIPKEYS         32843
#define ID_PLAYER_GODMODE               32844
#define ID_PLAYER_DEADLYBULLETS         32845
#define ID_PLAYER_RUBBERBULLETS         32846
#define ID_PLAYER_MASSIVEPLAYER         32847
#define ID_PLAYER_ABSORBERPLAYER        32848
#define ID_PLAYER_BOUNCINGPLAYER        32849
#define ID_PLAYER_AUTOPLAY              32850
#define ID_GAME_SPACEWAR                32851
#define ID_GAME_DESIGN                  32852
#define ID_PLAYER_CURSORCRITTER         32853
#define ID_PLAYER_ARROWKEYS             32854
#define ID_GAME_FREEPLAY                32855
#define ID_GAME_FREEPLAYWITHGRAVITYANDFRICTION 32856
#define ID_GAME_BOUNCE                  32857
#define ID_VIEW_WHOLEWORLD              32858
#define ID_VIEW_CLOSEUPONPLAYERREGION   32859
#define ID_VIEW_CENTERCLOSEUPONPLAYER   32860
#define ID_GAME_MAZEPLAY                32861
#define ID_GAME_BUBBLES                 32862
#define ID_GAME_PICKANDPOP              32865
#define ID_VIEW_SHOOTCURSOR             32866
#define ID_GAME_COLLIDECRITTERS         32869
#define ID_GAME_AIRHOCKEY               32870
#define ID_VIEW_OPENGLGRAPHICS          32871
#define ID_VIEW_MFCGRAPHICS             32872
#define ID_VIEW_TRANSLATEVIEWER         32873
#define ID_VIEWERRIDE                   32874
#define ID_VIEW_TRANSLATE               32875
#define ID_VIEW_RIDE                    32876
#define ID_VIEW_FLY                     32877
#define ID_VIEW_ORBIT                   32878
#define ID_VIEW_KEEPPLAYERINVIEW        32882
#define ID_VIEW_SOLIDBACKGROUND         32884
#define ID_VIEW_NOBACKGROUND            32885
#define ID_GAME_WORMS                   32886
#define ID_PLAYER_3DFLYER               32887
#define ID_VIEW_RESTORESTANDARDVIEWPOSITION 32888
#define ID_OPENGLINFODIALOG             32893
#define ID_GAME_3DDEFENDER              32894
#define ID_PLAYER_HOPPERCONTROL         32895
#define ID_GAME_3DMONSTERHALLWAY        32896
#define ID_GAME_QUAKESTYLEMMODELS       32897
#define ID_PLAYER_SCOOTERHOPPER3D       32898
#define ID_GAME_SPHERES                 32899
#define ID_VIEW_OPENGL_STEREO           32900
#define ID_GAME_SPACEWARWITHASUN        32901
#define ID_GAME_RACER                   32902
#define ID_GAME_3DSPACE                 32903
#define ID_VIEW_FULLSCREENVIEWNOMENUS   32904
#define ID_VIEW_FULLSCREEN              32904
#define ID_FULLSCREEN                   32905
#define ID_EXIT                         32906
#define ID_ABOUT                        32907
#define ID_USER_GUIDE                   57670

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        229
#define _APS_NEXT_COMMAND_VALUE         32909
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
